name: start1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Updated sdk constraint for compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core:
  firebase_auth:
  fluttertoast:
  cloud_firestore: ^5.0.0
  firebase_database:
  fl_chart:
  intl: ^0.18.0
  flutter_speed_dial:
  shared_preferences: ^2.0.15
  encrypt: ^5.0.3
  flip_card:
  url_launcher: ^6.1.10
  firebase_messaging:
  flutter_local_notifications:
  http:
  provider:

  # --- THE FIX ---
  # Removed the old 'telephony' package
  # Added the new, modern packages for SMS and permissions
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.0.1
  # --- END FIX ---


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icons.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icons.png"

